# Generated by Django 4.2.5 on 2023-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
                ('applied', models.BooleanField()),
                ('type_of_resume_sent', models.CharField(max_length=200)),
                ('date_applied', models.DateField()),
                ('hiring_manager', models.CharField(max_length=200)),
                ('hiring_manager_email', models.CharField(max_length=200)),
                ('hiring_manager_phone', models.IntegerField()),
                ('interview_status', models.CharField(max_length=200)),
                ('application_origin', models.CharField(max_length=200)),
                ('thankyou_sent', models.BooleanField()),
            ],
        ),
    ]
