# Generated by Django 4.2.5 on 2023-09-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='hiring_manager_phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='thankyou_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
