# Generated by Django 4.2.5 on 2023-09-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_hiring_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_manager_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
