# Generated by Django 4.2.5 on 2023-09-28 03:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_manager_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
