# Generated by Django 4.2.5 on 2023-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_hiring_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_manager_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
